controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
login:
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout
    controller: App\Controller\UserController::logout
fc_load_events:
    path: /fc-load-events
    controller: CalendarBundle\Controller\CalendarController::loadAction
    methods: GET
    defaults:
        start: null
        end: null
