parameters:
    # Tu peux ajouter des paramètres ici si nécessaire

services:

    # Configuration par défaut pour les services dans ce fichier
    _defaults:
        autowire: true      # Injection automatique des dépendances dans tes services
        autoconfigure: true # Inscrit automatiquement tes services comme commandes, abonnés aux événements, etc.

    # Déclaration de services pour les classes dans le dossier src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Déclaration explicite de ton service PhpMlService
    App\Service\PhpMlService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'  # Injecte l'EntityManager

 

    # Déclaration explicite du service pour la commande PredictCommand
    App\Command\PredictCommand: ~

    # Déclaration explicite du service pour la commande TrainModelCommand
    App\Command\TrainModelCommand: ~

    